### ISSUE TITLE
if model not pulled, error is cryptic

### ISSUE THREAD

**Issue by technovangelist** [ollama/ollama-js#18]
rather than any sensible error, i see this: 

```
           }
49 |             catch (error) {
50 |                 console.log('Failed to get text from error response');
51 |             }
52 |         }
53 |         throw new ResponseError(message, response.status);
                      ^
ReferenceError: Can't find variable: ResponseError
      at /Users/matt/projects/code/mmor/node_modules/ollama/dist/utils.js:53:18
      at fulfilled (/Users/matt/projects/code/mmor/node_modules/ollama/dist/utils.js:4:47)
```

pull the model and it works as expected

**Comment by BruceMacD** [comment]
Thanks for the report Matt, fixed in 05d4b5ab82ebf5945dc73bebcfe8d3ffa37ab5cd which will be in the next release
