### ISSUE TITLE
not compatible with CJS module

### ISSUE THREAD

**Issue by himself65** [ollama/ollama-js#44]
```shell
/Users/himself65/Library/Application Support/fnm/node-versions/v18.19.0/installation/lib/node_modules/ts-node/dist/index.js:851
            return old(m, filename);
                   ^
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/himself65/Code/LlamaIndexTS/node_modules/.pnpm/ollama@0.4.6/node_modules/ollama/dist/index.js from /Users/himself65/Code/LlamaIndexTS/packages/core/dist/ServiceContext.js not supported.
Instead change the require of index.js in /Users/himself65/Code/LlamaIndexTS/packages/core/dist/ServiceContext.js to a dynamic import() which is available in all CommonJS modules.
    at require.extensions.<computed> [as .js] (/Users/himself65/Library/Application Support/fnm/node-versions/v18.19.0/installation/lib/node_modules/ts-node/dist/index.js:851:20)
    at Object.<anonymous> (/Users/himself65/Code/LlamaIndexTS/packages/core/dist/ServiceContext.js:7:1)
    at require.extensions.<computed> [as .js] (/Users/himself65/Library/Application Support/fnm/node-versions/v18.19.0/installation/lib/node_modules/ts-node/dist/index.js:851:20)
    at Object.<anonymous> (/Users/himself65/Code/LlamaIndexTS/packages/core/dist/index.js:11:22)
    at require.extensions.<computed> [as .js] (/Users/himself65/Library/Application Support/fnm/node-versions/v18.19.0/installation/lib/node_modules/ts-node/dist/index.js:851:20)
    at Object.<anonymous> (/Users/himself65/Code/LlamaIndexTS/examples/ollama.ts:10:22)
    at m._compile (/Users/himself65/Library/Application Support/fnm/node-versions/v18.19.0/installation/lib/node_modules/ts-node/dist/index.js:857:29)
    at require.extensions.<computed> [as .ts] (/Users/himself65/Library/Application Support/fnm/node-versions/v18.19.0/installation/lib/node_modules/ts-node/dist/index.js:859:16)
    at phase4 (/Users/himself65/Library/Application Support/fnm/node-versions/v18.19.0/installation/lib/node_modules/ts-node/dist/bin.js:466:20)
    at bootstrap (/Users/himself65/Library/Application Support/fnm/node-versions/v18.19.0/installation/lib/node_modules/ts-node/dist/bin.js:54:12)
    at main (/Users/himself65/Library/Application Support/fnm/node-versions/v18.19.0/installation/lib/node_modules/ts-node/dist/bin.js:33:12)
    at Object.<anonymous> (/Users/himself65/Library/Application Support/fnm/node-versions/v18.19.0/installation/lib/node_modules/ts-node/dist/bin.js:579:5) {
  code: 'ERR_REQUIRE_ESM'

```

**Comment by JonoLF** [comment]
try either changing your file extension to .cjs to use the 'require' syntax, or define your project as a 'module' in your package.json, and then rather use the ES 'import' syntax. That's what worked for me.

**Comment by saul-jb** [comment]
You can use it in a CommonJS project using dynamic import:
```javascript
const { Ollama } = await import('ollama')
```

Or alternatively change your package system to ESM (set `"type":  "module"` in package.json)`
```javascript
import { Ollama } from 'ollama'
```

**Comment by BruceMacD** [comment]
This should work now in the most recent release, `v0.5.0`. Thanks to all the contributors.
