### ISSUE TITLE
An error occurred while packing in electron

### ISSUE THREAD

**Issue by whl1207** [ollama/ollama-js#79]
The following message is displayed when installing ‘npm i ollama’ and then packing with electron:

• electron-builder  version=24.5.2 os=10.0.19045
  • loaded configuration  file=package.json ("build" field)
  • description is missed in the package.json  appPackageFile=E:\Project\Knowledge\package.json
  • author is missed in the package.json  appPackageFile=E:\Project\Knowledge\package.json
  • writing effective config  file=release\builder-effective-config.yaml
  • executing @electron/rebuild  arch=x64 platform=windows version=25.2.0 appDir=E:\Project\Knowledge
Error: Could not find any Python installation to use
    at PythonFinder.fail (E:\Project\Knowledge\node_modules\node-gyp\lib\find-python.js:330:47)
    at PythonFinder.runChecks (E:\Project\Knowledge\node_modules\node-gyp\lib\find-python.js:159:21)
    at PythonFinder.<anonymous> (E:\Project\Knowledge\node_modules\node-gyp\lib\find-python.js:228:18)
    at PythonFinder.execFileCallback (E:\Project\Knowledge\node_modules\node-gyp\lib\find-python.js:294:16)
    at exithandler (node:child_process:427:5)
    at ChildProcess.errorhandler (node:child_process:439:5)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

  ⨯ node-gyp failed to rebuild 'E:\Project\Knowledge\node_modules\canvas'  failedTask=build stackTrace=Error: node-gyp failed to rebuild 
'E:\Project\Knowledge\node_modules\canvas'
    at ChildProcess.<anonymous> (E:\Project\Knowledge\node_modules\@electron\rebuild\src\module-type\node-gyp\node-gyp.ts:131:16)        
    at ChildProcess.emit (node:events:513:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)

**Comment by BruceMacD** [comment]
Hi @whl1207, ollama-js uses Node, but I believe that Electron uses Node so this should work. It looks like you may need Python configured on your system to build the `node-gyp` dependency in this case. Does building other node packages work?

**Comment by whl1207** [comment]
> Hi @whl1207, ollama-js uses Node, but I believe that Electron uses Node so this should work. It looks like you may need Python configured on your system to build the `node-gyp` dependency in this case. Does building other node packages work?

Thank you for your help. electron uses nodejs. When I installed python, the packaging still prompts me to install Visual Studio, do I have to use vs studio to use ollama-js? The specific error is as follows:
`Error: Could not find any Visual Studio installation to use
    at VisualStudioFinder.fail (D:\Project\Knowledge\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
    at D:\Project\Knowledge\node_modules\node-gyp\lib\find-visualstudio.js:75:16
    at VisualStudioFinder.findVisualStudio2013 (D:\Project\Knowledge\node_modules\node-gyp\lib\find-visualstudio.js:380:14)
    at D:\Project\Knowledge\node_modules\node-gyp\lib\find-visualstudio.js:71:14
    at VisualStudioFinder.findVisualStudio2015 (D:\Project\Knowledge\node_modules\node-gyp\lib\find-visualstudio.js:364:14)
    at D:\Project\Knowledge\node_modules\node-gyp\lib\find-visualstudio.js:67:12
    at failPowershell (D:\Project\Knowledge\node_modules\node-gyp\lib\find-visualstudio.js:156:7)
    at VisualStudioFinder.parseData (D:\Project\Knowledge\node_modules\node-gyp\lib\find-visualstudio.js:170:14)
    at D:\Project\Knowledge\node_modules\node-gyp\lib\find-visualstudio.js:143:14
    at ChildProcess.exithandler (node:child_process:414:7)

  ⨯ node-gyp failed to rebuild 'D:\Project\Knowledge\node_modules\canvas'  failedTask=build stackTrace=Error: node-gyp failed to rebuild 'D:\Project\Knowledge\node_modules\canvas'
    at ChildProcess.<anonymous> (D:\Project\Knowledge\node_modules\@electron\rebuild\src\module-type\node-gyp\node-gyp.ts:131:16)
    at ChildProcess.emit (node:events:517:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:292:12)`

**Comment by supertick** [comment]
node-gyp is used to deal with native dependencies - so you are in windows, and its trying to find a compiler.
This has nothing to do with ollama-js, it has something to do with some other dependency you project has and the Electron build
